version: "3.9"
services:
  couch:
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    build: ./homebrewerdb
    ports:
       - "5984:5984"
  api:
    tty: true
    stdin_open: true
    build: ./homebrewerapi
    volumes:
      - ./homebrewerapi:/homebrewerapi
      - ./homebrewerapi/node_modules:/homebrewerapi/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    links:
      - couch
    depends_on:
      - couch