version: "3.9"
services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  couch:
    container_name: homebrewer_couchdb
    image: couchdb:3.1.0
    restart: always
    ports:
      - 5984:5984
    environment:
      - NODENAME=10.0.0.10
      - ERL_FLAGS=-setcookie monster
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./config/couchdb:/opt/couchdb/etc/local.d
      - ./data/couchdb/1:/opt/couchdb/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`db.localhost`)"
      - "traefik.http.routers.db.entrypoints=web"
    networks:
      default:
      couchdb-net:
        ipv4_address: 10.0.0.10
  
  clouseau:
    image: openjdk:8
    command: >
      java -server
      -classpath '/app/*'
      -Xmx2G -Dsun.net.inetaddr.ttl=30
      -Dsun.net.inetaddr.negative.ttl=30
      -Dlog4j.configuration=file:/config/log4j.properties
      -XX:OnOutOfMemoryError="kill -9 %p"
      -XX:+UseConcMarkSweepGC
      -XX:+CMSParallelRemarkEnabled com.cloudant.clouseau.Main /config/clouseau.ini
    restart: always
    depends_on:
      - couch
    volumes:
      - ./config/clouseau:/config
      - ./data/clouseau/1:/data
      - ./clouseau-2.17.0:/app
    network_mode: service:couch
  
  api:
    container_name: homebrewer_node_api
    tty: true
    stdin_open: true
    build: ./homebrewerapi
    volumes:
      - ./homebrewerapi:/homebrewerapi
      - ./homebrewerapi/node_modules:/homebrewerapi/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
      - "9229:9229"
    links:
      - couch
    depends_on:
      - couch
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"

networks:
  couchdb-net:
    name: couchdb-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24